name: CI Pipeline

on: 
    push:

    pull_request:
     branches:
      -dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Step1: Checkout the code from the repository
      - name: checkout code
        uses: actions/checkout@v3


      #Step2: set up Node js environment (use a specific Node js version)
      - name : Set up Node.js
        uses: actions/setup-node@v3
        with :
          node-version: '18'

      
      #Step3: Install dependencies
      - name: Install dependencies
        run: npm install


      #Step5: 
      - name: Upload production build artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: production-build
          path: dist/


      #Step7: Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token : ${{ secrets.GITHUB_TOKEN}}
            publish_dir: ./dist

  publish:
    runs-on: ubuntu-latest

    steps:
      #Step1: Checkout the code from the repository
      - name: checkout code
        uses: actions/checkout@v3

      - name : Set up Node.js
        uses: actions/setup-node@v3
        with :
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npm run build
        
      #Step5: 
      - name: Upload production build artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: production-build
          path: dist/


      #Step7: Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token : ${{ secrets.GITHUB_TOKEN}}
            publish_dir: ./dist
