name: CI Pipeline

on: 
    pull_request:
     branches:
      -dev

jobs:
  build:
    runs-on: ubunto-latest

    steps:
      #Step1: Checkout the code from the repository
      - name: checkout code
        uses: actions/checkout@v3


      #Step2: set up Node js environment (use a specific Node js version)
      - name : Set up Node.js
        uses: actions/setup-node@v3
        with :
          node-version: '18'

      
      #Step3: Install dependencies
      - name: Install dependencies
        run: npm install
